// Generated by CoffeeScript 1.3.3
(function() {
  var person;

  person = {
    good: true,
    bad: true
  };

  if (person.good === true && person.bad !== false) {
    alert("This is impossible");
  }

}).call(this);
