// Generated by CoffeeScript 1.3.3
(function() {
  var good, score, v_good, _i, _len, _ref;

  good = [];

  v_good = [];

  _ref = [60, 45, 56, 90, 95, 0];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    score = _ref[_i];
    (score > 60 ? good : v_good).push(score);
  }

  alert(good);

  alert(v_good);

}).call(this);
