// Generated by CoffeeScript 1.3.3
(function() {
  var myArr, number, _i, _len;

  myArr = [1, 2, 3];

  for (_i = 0, _len = myArr.length; _i < _len; _i++) {
    number = myArr[_i];
    alert(number);
  }

}).call(this);
