// Generated by CoffeeScript 1.3.3
(function() {
  var sum,
    __slice = [].slice;

  sum = function() {
    var nums, result;
    nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = 0;
    nums.forEach(function(n) {
      return result += n;
    });
    return result;
  };

  alert(sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));

}).call(this);
