// Generated by CoffeeScript 1.3.3
(function() {
  var prisoner, prisoners, _i, _len;

  prisoners = ["Roger", "Roderick", "Brian"];

  for (_i = 0, _len = prisoners.length; _i < _len; _i++) {
    prisoner = prisoners[_i];
    if (prisoner[0] === "R") {
      alert(prisoner);
    }
  }

}).call(this);
