// Generated by CoffeeScript 1.3.3
(function() {
  var myObj, third, _ref;

  myObj = {
    first: "name1",
    second: "name2"
  };

  third = (_ref = myObj.first) != null ? _ref : "new_name";

  alert(myObj.first);

  alert(third);

}).call(this);
