// Generated by CoffeeScript 1.3.3
(function() {
  var first, last, names;

  names = {
    sam: "seaborn",
    donna: "moss"
  };

  for (first in names) {
    last = names[first];
    alert("" + first + " " + last);
  }

}).call(this);
